# Generated by Django 4.2.7 on 2023-11-10 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('nombre', models.CharField(max_length=20)),
                ('apellidos', models.CharField(max_length=40)),
                ('dni', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombreUser', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
